language: r
cache: packages
sudo: true

before_install:
    - ./travis-install.sh

r:
#    - oldrel
    - release
#    - devel

os:
    - linux
#    - osx

matrix:
    fast_finish: true
    allow_failures:
        - r: devel

branches:
    only:
        - master
